### ISSUE TITLE
[BUG] Serverless exclude sections are not working as expected

### ISSUE THREAD

**Issue by wickstargazer** [flowaccount/nx-plugins#18]
**Describe the bug**
```
service: hello-world
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - src/**
  include:
    - src/function/handler.js
  custom:
    enable_optimize:
      local: false
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
functions:
  config:
    handler: src/handler.hello
```

the exclude is not getting excluded

**To Reproduce**

**Expected behavior**

**Screenshots**

**Check which provider is affected:**
[x] AWS
[] Azure
[] Google Cloud Platform

**Check which framework is affected:**
[] Angular
[] Nodejs
[x] Serverless
[] Lambda
[] Infrastructure as a code

**Additional context**
