### ISSUE TITLE
[BUG] Could not check for peer dependencies of x package

### ISSUE THREAD

**Issue by hoang-innomizetech** [flowaccount/nx-plugins#36]
I am getting below warning when deploying our service

```
getting external modules
create a package.json with first level dependencies
Serverless: WARNING: Could not check for peer dependencies of serverless-mysql
generate lock entry for yarn for dependency graph to work.
get the packagelist with dependency graph and depth=2 level
re-writing package.json with dependency-graphs
Serverless: WARNING: Could not determine version of module tslib
Serverless: WARNING: Could not check for peer dependencies of serverless-mysql
run packager to  install node_modules
```

Here is the sample code of my Lambda function

```
// Require and initialize outside of your main handler
import * as serverlessMysql from 'serverless-mysql';
const mysql = serverlessMysql({
  config: {
    host     : process.env.ENDPOINT,
    database : process.env.DATABASE,
    user     : process.env.USERNAME,
    password : process.env.PASSWORD
  }
})

// Main handler function
export const handler = async (event, context) => {
  // Run your query
  let results = await mysql.query('SELECT * FROM table')

  // Run clean up function
  await mysql.end()

  // Return the results
  return results
}
```

I have debugged and figured out that the modulePackagePath is invalid (the root dir is duplicated in the path), see below example

modulePackagePath /Users/hoangle/Documents/Working/Source/my-sls-api/Users/hoangle/Documents/Working/Source/my-sls-api/node_modules/serverless-mysql/package.json

**Comment by wickstargazer** [comment]
Can i see your serverless.yml

Also are you trying to deploy by function or the whole thing?

**Comment by hoang-innomizetech** [comment]
The serverless.yml is straightforward

```
service: myapi
frameworkVersion: ">=1.1.0 <2.0.0"
plugins:
  - serverless-offline
package:
  individually: true
  excludeDevDependencies: true
  custom:
    enable_optimize:
      local: false
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: recom_dev

functions:
  hello-world:
    handler: src/hello-world/hello-world.handler
    events:
      - http:
          path: hello-world
          method: get


```

The workspace.json also default
