### ISSUE TITLE
[BUG] Cannot Include Json Schema in serverless.yml

### ISSUE THREAD

**Issue by brian-weasner** [flowaccount/nx-plugins#87]
**Describe the bug**
Serverless fails to add a Json Schema to my Http Post Request due to "File not Found".

Added Json Schema to `serverless.yml` the same way as described here: [Serverless Request Schema Validators](https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#request-schema-validators)

**To Reproduce**
1. Create a valid json schema json object (Verified that my schema is valid)
2. Add it to the project
3. Add the schema to the serverless http handler event with the proper file location in `serverless.yml`
4. Serve in offline mode (not sure if this happens when built for production)

**Expected behavior**
I should not have a warning about the schema not being found, and it should be used to validate my request

**Screenshots**
Serverless yml file
```yml
functions:
  location:
    handler: src/controllers/location.saveLocation
    events:
      - http:
          path: location
          method: post
          request:
            schemas:
              application/json: ${file(src/schemas/location.json)}
```

Cmd Output
```console
running process
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Load command prune
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio

 Serverless Warning --------------------------------------

  A valid file to satisfy the declaration 'file(src/schemas/location.json)' could not be found.

Serverless: Invoke offline
```

Schema File Location:
![image](https://user-images.githubusercontent.com/84519320/124978246-866ee080-dfff-11eb-9355-27d31290c632.png)

**Check which provider is affected:**
[x] AWS
[ ] Azure
[ ] Google Cloud Platform

**Check which framework is affected:**
[ ] Angular
[ ] Nodejs
[x] Serverless
[ ] Lambda
[ ] Infrastructure as a code

**Additional context**
- Things I have tried:
  - Moving schema to root of app (next to `serverless.yml` and updating file path) (Does not work) 
  - Console logging the file when using require() from the location handler (WORKS)
  - Adding `"resolveJsonModule": true` to `tsconfig.json` (Helps with import/require within ts, didn't help with this issue)
  - Adding Assets to the build options to copy the schema files to the `dist` folder (Did not work)
    - Tried multiple paths
 - Looks like its related to: #23 although that issue seemed to be a serverless issue and has since been fixed.

**Comment by brian-weasner** [comment]
Note: Not the same as https://github.com/dherault/serverless-offline/issues/894, as I am expecting serverless to find the schema, and at least use it when deployed.

**Comment by tstackhouse** [comment]
I've ran into this, I don't have the code in front of me, but the workaround is to do something like this in your serverless.yml

```
functions:
  location:
    handler: src/controllers/location.saveLocation
    events:
      - http:
          path: location
          method: post
          request:
            schemas:
              application/json:
                - ${file(src/schemas/location.json)}
                - ${file(apps/my-app/src/schemas/location.json)}
```

The syntax might be different, I'd have to look at my config at $WORK, but that's the gist, you need to define the path twice, once for offline and once for APIGW, because of path resolution differrences.  You might also need to make sure that the packaging step is including your schema in the generated zip file.
